export const UPLOAD = "UPLOAD";
export const GET_POSTS = "GET_POSTS";
export const GET_FILTERED_POSTS = "GET_FILTERED_POSTS";
export const NO_POSTS_FOUND = "NO_POSTS_FOUND";
export const SET_EXPLORE_STATUS = "SET_EXPLORE_STATUS";
